FlightBookingApp/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FlightBookingApp.Models;

public partial class Flight
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Flightid { get; set; }

    [Required(ErrorMessage = "Flight name is required")]
    public string Name { get; set; } = null!;

    [Required(ErrorMessage = "Source is required")]
    public string Source { get; set; } = null!;

    [Required(ErrorMessage = "Destination is required")]
    public string Destination { get; set; } = null!;

    [Required(ErrorMessage = "Departure time is required")]
    [DataType(DataType.DateTime)]
    [Display(Name = "Departure Time")]
    public DateTime Departuretime { get; set; }

    [Required(ErrorMessage = "Arrival time is required")]
    [DataType(DataType.DateTime)]
    [Display(Name = "Arrival Time")]
    public DateTime Arrivaltime { get; set; }

    [Required(ErrorMessage = "Rate is required")]
    [DataType(DataType.Currency)]
    public decimal Rate { get; set; }

    [Required(ErrorMessage = "Capacity is required")]
    public int Capacity { get; set; }

    [Required(ErrorMessage = "Status is required")]
    public string Status { get; set; } = null!;


    [Display(Name = "Currently Booked")]
    public int Currentlybookedseats { get; set; } = 0;

    [Required(ErrorMessage = "Flight code is required")]
    public string Code { get; set; } = null!;

    public override string ToString()
    {
        return $"Flight ID: {Flightid}, Name: {Name}, Source: {Source}, Destination: {Destination}, " +
               $"Departure Time: {Departuretime}, Arrival Time: {Arrivaltime}, Rate: {Rate}, " +
               $"Capacity: {Capacity}, Status: {Status}, Currently Booked Seats: {Currentlybookedseats}, " +
               $"Code: {Code}";
    }

    public virtual ICollection<Bookingdetail> Bookingdetails { get; set; } = new List<Bookingdetail>();
}

FlightBookingApp/Controllers/FlightController.cs
using FlightBookingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlightBookingApp.Controllers;

public class FlightController : Controller
{
    private readonly PostgresContext _db;
    private readonly ILogger<FlightController> _logger;

    public FlightController(PostgresContext db,ILogger<FlightController> logger)
    {
        _db = db;
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View(_db.Flights.OrderBy(f=>f.Name));
    }
    
    public IActionResult Add()
    {
        String? isAdmin = HttpContext.Session.GetString("Email");
        if (isAdmin == null)
        {
            return RedirectToAction("Login", "Customer");
        }

        if (!isAdmin.ToLower().Equals("admin@admin.com"))
        {
            TempData["ErrorMessage"] = "Not authorized to add a flight";
            return RedirectToAction("Login", "Customer");
        }
        ViewBag.StatusOptions = new List<string> { "Scheduled", "Delayed", "Cancelled" };
        return View();
    }

    [HttpPost]
    public IActionResult Add(Flight newFlight)
    {
        //* repopulating
        ViewBag.StatusOptions = new List<string> { "Scheduled", "Delayed", "Cancelled" };
        try
        {
            if (!ModelState.IsValid)
            {
                return View(newFlight);
            }
            Flight? existingFlight = _db.Flights.FirstOrDefault(f => f.Code.ToLower().Equals(newFlight.Code.ToLower()));
            if (existingFlight != null)
            {
                ModelState.AddModelError("Code","A flight with this code already exists");
                return View(existingFlight);
            }

            if (newFlight.Arrivaltime <= newFlight.Departuretime)
            {
                ViewBag.ErrorMessage = "Arrival time cannot be less than departure time";
                return View(existingFlight);

            }

            if (newFlight.Departuretime < DateTime.Now)
            {
                ModelState.AddModelError("Departuretime","Select a future date");
                return View(existingFlight);
            }
            if (newFlight.Arrivaltime < DateTime.Now)
            {
                ModelState.AddModelError("Arrivaltime","Select a future date");
                return View(existingFlight);

            }
            
            // Console.WriteLine(newFlight);
            newFlight.Code = newFlight.Code.ToUpper();
            _db.Flights.Add(newFlight);
            _db.SaveChanges();
            TempData["SuccessMessage"] = "Flight Added successfully.";
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            ViewBag.ErrorMessage="An error occurred while creating the account. Please try again.";
            return View(newFlight);
        }
    }
    
    public IActionResult Details(int id)
    {
        try
        {
            Flight? f = _db.Flights.Find(id);

            if (f == null)
            {
                TempData["ErrorMessage"] = "Flight does not exist";
                return RedirectToAction("Index");
            }
            else
            {
                return View(f);
            }
        }
        catch (Exception e)
        {
            // Console.WriteLine($"Error: {e.Message}");
            TempData["ErrorMessage"]="An error occurred while fetching the flight details. Please try again.";
            return RedirectToAction("Index");
        }
    }
    
    public IActionResult Edit(int id)
    {
        String? isAdmin = HttpContext.Session.GetString("Email");
        if (isAdmin == null)
        {
            return RedirectToAction("Login", "Customer");
        }

        if (!isAdmin.ToLower().Equals("admin@admin.com"))
        {
            TempData["ErrorMessage"] = "Not authorized to edit a flight";
            return RedirectToAction("Login", "Customer");
        }
        ViewBag.StatusOptions = new List<string> { "Scheduled", "Delayed", "Cancelled" };
        try
        {
            Flight? f = _db.Flights.Find(id);

            if (f == null)
            {
                TempData["ErrorMessage"] = "Flight does not exist";
                return RedirectToAction("Index");
            }
            else
            {
                return View(f);
            }
        }
        catch (Exception e)
        {
            // Console.WriteLine($"Error: {e.Message}");
            TempData["ErrorMessage"]="An error occurred while fetching the flight details. Please try again.";
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    public IActionResult Edit(Flight upflight)
    {
        ViewBag.StatusOptions = new List<string> { "Scheduled", "Delayed", "Cancelled" };

        try
        {
            Flight? existingFlight = _db.Flights.AsNoTracking().FirstOrDefault(f => f.Flightid == upflight.Flightid);
            if (existingFlight == null)
            {
                TempData["ErrorMessage"] = "Flight does not exist";
                return RedirectToAction("Index");
            }
            
            Flight? existingFlightWithSameCode = _db.Flights.FirstOrDefault(f => f.Code.ToLower().Equals(upflight.Code.ToLower()) && f.Flightid!=upflight.Flightid);
            if (existingFlightWithSameCode != null)
            {
                ModelState.AddModelError("Code","A flight with this code already exists");
                return View(upflight);
            }

            _db.Flights.Update(upflight);
            _db.SaveChanges();
            TempData["SuccessMessage"] = "Flight updated successfully.";


            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"]="An error occurred while fetching the flight details. Please try again.";
            return RedirectToAction("Index");
        }
        
    }

    public IActionResult Cancel(int id)
    {
        String? isAdmin = HttpContext.Session.GetString("Email");
        if (isAdmin == null)
        {
            return RedirectToAction("Login", "Customer");
        }

        if (!isAdmin.ToLower().Equals("admin@admin.com"))
        {
            TempData["ErrorMessage"] = "Not authorized to cancel a flight";
            return RedirectToAction("Login", "Customer");
        }
        try
        {
            Flight? f = _db.Flights.Find(id);

            if (f == null)
            {
                TempData["ErrorMessage"] = "Flight does not exist";
                return RedirectToAction("Index");
            }
            else
            {
                return View(f);
            }
        }
        catch (Exception e)
        {
            // Console.WriteLine($"Error: {e.Message}");
            TempData["ErrorMessage"]="An error occurred while fetching the flight details. Please try again.";
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    [ActionName("Cancel")]
    public IActionResult CancelConfirmed(int id)
    {
        try
        {
            Flight? f = _db.Flights.Find(id);
    
            if (f == null)
            {
                TempData["ErrorMessage"] = "Flight does not exist";
                return RedirectToAction("Index");
            }

            f.Status = "Cancelled";
                _db.SaveChanges();
                TempData["SuccessMessage"] = "Flight Cancelled successfully.";
                return RedirectToAction("Index");
            
        }
        catch (Exception e)
        {
            Console.WriteLine($"Error: {e.Message}");
            TempData["ErrorMessage"]="An error occurred while fetching the account details. Please try again.";
            return RedirectToAction("Index");
        }
    }
    
}

FlightBookingApp/Views/Flight/Add.cshtml
@model FlightBookingApp.Models.Flight

@{
    ViewData["Title"] = "Add";
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @ViewBag.ErrorMessage
    </div>
}

<h1>Add a flight</h1>

<br />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departuretime" class="control-label"></label>
                <input asp-for="Departuretime" class="form-control" />
                <span asp-validation-for="Departuretime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Arrivaltime" class="control-label"></label>
                <input asp-for="Arrivaltime" class="form-control" />
                <span asp-validation-for="Arrivaltime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                @Html.DropDownListFor(model=>model.Status,new SelectList(ViewBag.StatusOptions),"Select Status", new { @class = "form-control"})
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@* <div> *@
@*     <a asp-action="Index">Back to List</a> *@
@* </div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlightBookingApp/Views/Flight/Cancel.cshtml
@model FlightBookingApp.Models.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Are you sure you want to delete this flight?</h1>

<div>
    
    <br />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flightid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flightid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departuretime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departuretime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Arrivaltime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Arrivaltime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currentlybookedseats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currentlybookedseats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
    </dl>
    
    <form asp-action="Cancel" method="post">
        <input type="submit" value="Cancel" class="btn btn-danger" /> 
    </form>
</div>

FlightBookingApp/Views/Flight/Details.cshtml
@model FlightBookingApp.Models.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Flight Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flightid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flightid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departuretime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departuretime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Arrivaltime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Arrivaltime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currentlybookedseats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currentlybookedseats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
    </dl>
</div>
<div>
    @* @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) | *@
    <a style="background-color: #0c63e4" class="btn btn-secondary" href="@Url.Action("Edit", "Flight",new{id=Model.Flightid})">Edit</a>
    @* <a asp-action="Index">Back to List</a> *@
</div>

FlightBookingApp/Views/Flight/Edit.cshtml
@model FlightBookingApp.Models.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Flight</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                            <label asp-for="Flightid" class="control-label"></label>
                            <input asp-for="Flightid" class="form-control" readonly/>
                            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departuretime" class="control-label"></label>
                <input asp-for="Departuretime" class="form-control" />
                <span asp-validation-for="Departuretime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Arrivaltime" class="control-label"></label>
                <input asp-for="Arrivaltime" class="form-control" />
                <span asp-validation-for="Arrivaltime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                @Html.DropDownListFor(model=>model.Status,new SelectList(ViewBag.StatusOptions),"Select Status", new { @class = "form-control"})
                
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currentlybookedseats" class="control-label"></label>
                <input asp-for="Currentlybookedseats" class="form-control" />
                <span asp-validation-for="Currentlybookedseats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@* <div> *@
@*     <a asp-action="Index">Back to List</a> *@
@* </div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlightBookingApp/Views/Flight/Index.cshtml
@model IEnumerable<FlightBookingApp.Models.Flight>

@{
    ViewData["Title"] = "Index";
    
    if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }
    
    if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }
}

<h1>All Flights</h1>

<p>
    <a style="background-color: #0c63e4" class="btn btn-secondary" href="@Url.Action("Add", "Flight")">Add</a>
</p>
<table class="table">
    <thead>
        <tr>
            @* <th> *@
            @*     @Html.DisplayNameFor(model => model.Flightid) *@
            @* </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            @* <th> *@
            @*     @Html.DisplayNameFor(model => model.Departuretime) *@
            @* </th> *@
            @* <th> *@
            @*     @Html.DisplayNameFor(model => model.Arrivaltime) *@
            @* </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Rate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Currentlybookedseats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @* <td> *@
            @*     @Html.DisplayFor(modelItem => item.Flightid) *@
            @* </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            @* <td> *@
            @*     @Html.DisplayFor(modelItem => item.Departuretime) *@
            @* </td> *@
            @* <td> *@
            @*     @Html.DisplayFor(modelItem => item.Arrivaltime) *@
            @* </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Rate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Currentlybookedseats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                
                <a style="background-color: #0c63e4" class="btn btn-secondary" href="@Url.Action("Edit", "Flight",new{id=item.Flightid})">Edit</a>
                <a style="background-color: #0c63e4" class="btn btn-secondary" href="@Url.Action("Details", "Flight",new {id=item.Flightid})">Details</a>
                @{
                    if (!item.Status.Equals("Cancelled"))
                    {
                        <a style="background-color: #0c63e4" class="btn btn-secondary" href="@Url.Action("Cancel", "Flight",new {id=item.Flightid})">Cancel</a>
                        
                    }
                }
                
                @* @Html.ActionLink("Edit", "Edit", new {  id=item.Flightid }) | *@
                @* @Html.ActionLink("Details", "Details", new { id=item.Flightid }) | *@
                @* @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) *@
            </td>
        </tr>
}
    </tbody>
</table>